name: build
on:
  push:
    tags:
      - "v*"
jobs:
  arm64-build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - name: Setup torch
        run: |
          curl -L https://anaconda.org/pytorch/pytorch/1.13.1/download/osx-arm64/pytorch-1.13.1-py3.9_0.tar.bz2 | tar -xv
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH=${{ github.workspace }}/lib/python3.9/site-packages/torch -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64
          make -j
      - name: Package creation
        run: |
          mkdir torchplugins
          mkdir torchplugins/help
          mv externals torchplugins
          cp src/maxmsp/fc/fc.maxhelp torchplugins/help
          cp src/maxmsp/filterbank_tilde/filterbank~.maxhelp torchplugins/help
          tar -czvf torchplugins_macOS_arm64.tar.gz torchplugins
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: torchplugins
          path: torchplugins_macOS_arm64.tar.gz

  x86_64-build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - name: Setup torch
        run: |
          curl -L https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.13.1.zip -o libtorch.zip
          unzip libtorch.zip

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH=${{ github.workspace }}/libtorch -DCMAKE_BUILD_TYPE=Release
          make -j
      - name: Package creation
        run: |
          mkdir torchplugins
          mkdir torchplugins/help
          mv externals torchplugins
          cp src/maxmsp/fc/fc.maxhelp torchplugins/help
          cp src/maxmsp/filterbank_tilde/filterbank~.maxhelp torchplugins/help
          tar -czvf torchplugins_macOS_x86_64.tar.gz torchplugins
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: torchplugins
          path: torchplugins_macOS_x86_64.tar.gz

  AutomaticRelease:
    runs-on: ubuntu-latest
    needs: [arm64-build, x86_64-build]
    steps:
      - name: Download build binaries
        uses: actions/download-artifact@v2
        with:
          name: torchplugins
      - name: Automated Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            torchplugins_macOS_x86_64.tar.gz
            torchplugins_macOS_arm64.tar.gz
